IF EXISTS(select 1 from sys.databases where [name]='RakaposhiDB')
	DROP DATABASE [RakaposhiDB]
GO
USE [master]
CREATE DATABASE [RakaposhiDB]
GO

USE [RakaposhiDB]
GO
/****** Object:  Table [dbo].[ROLETABLE]    Script Date: 09/08/2022 3:48:29 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLETABLE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[Description] [nvarchar](50) NULL,
 CONSTRAINT [PK_USERROLETABLE] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRANSLINE]    Script Date: 09/08/2022 3:48:29 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRANSLINE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[TransId] [bigint] NOT NULL,
	[FuncId] [bigint] NOT NULL,
 CONSTRAINT [PK_TRANSLINE] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRANSTABLE]    Script Date: 09/08/2022 3:48:29 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRANSTABLE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NOT NULL,
	[Transtype] [bigint] NOT NULL,
	[Amount] [decimal](18, 2) NOT NULL,
	[Date] [datetime] NOT NULL,
 CONSTRAINT [PK_TRANSTABLE] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRANSTYPE]    Script Date: 09/08/2022 3:48:29 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRANSTYPE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](10) NOT NULL,
	[Description] [nvarchar](50) NULL,
 CONSTRAINT [PK_TRANSTYPE] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERIMAGE]    Script Date: 09/08/2022 3:48:29 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERIMAGE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[Image] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_USERIMAGE] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERROLETABLE]    Script Date: 09/08/2022 3:48:29 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERROLETABLE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NOT NULL,
	[RoleId] [bigint] NOT NULL,
 CONSTRAINT [PK_USERROLETABLE_1] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERSTATUS]    Script Date: 09/08/2022 3:48:29 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERSTATUS](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[Status] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERTABLE]    Script Date: 09/08/2022 3:48:29 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERTABLE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[Password] [nvarchar](20) NOT NULL,
	[Status] [bigint] NOT NULL,
	[Image] [bigint] NOT NULL,
 CONSTRAINT [PK_USERTABLE] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERTABLE] ADD  CONSTRAINT [default_status]  DEFAULT ((2)) FOR [Status]
GO
ALTER TABLE [dbo].[TRANSLINE]  WITH CHECK ADD  CONSTRAINT [FK_TRANSLINE_TRANSTABLE] FOREIGN KEY([TransId])
REFERENCES [dbo].[TRANSTABLE] ([RecId])
GO
ALTER TABLE [dbo].[TRANSLINE] CHECK CONSTRAINT [FK_TRANSLINE_TRANSTABLE]
GO
ALTER TABLE [dbo].[TRANSTABLE]  WITH CHECK ADD  CONSTRAINT [FK_TRANSTABLE_TRANSTYPE] FOREIGN KEY([Transtype])
REFERENCES [dbo].[TRANSTYPE] ([RecId])
GO
ALTER TABLE [dbo].[TRANSTABLE] CHECK CONSTRAINT [FK_TRANSTABLE_TRANSTYPE]
GO
ALTER TABLE [dbo].[TRANSTABLE]  WITH CHECK ADD  CONSTRAINT [FK_TRANSTABLE_USERTABLE] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERTABLE] ([RecId])
GO
ALTER TABLE [dbo].[TRANSTABLE] CHECK CONSTRAINT [FK_TRANSTABLE_USERTABLE]
GO
ALTER TABLE [dbo].[USERROLETABLE]  WITH CHECK ADD  CONSTRAINT [FK_USERROLETABLE_ROLETABLE] FOREIGN KEY([RoleId])
REFERENCES [dbo].[ROLETABLE] ([RecId])
GO
ALTER TABLE [dbo].[USERROLETABLE] CHECK CONSTRAINT [FK_USERROLETABLE_ROLETABLE]
GO
ALTER TABLE [dbo].[USERROLETABLE]  WITH CHECK ADD  CONSTRAINT [FK_USERROLETABLE_USERTABLE] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERTABLE] ([RecId])
GO
ALTER TABLE [dbo].[USERROLETABLE] CHECK CONSTRAINT [FK_USERROLETABLE_USERTABLE]
GO
ALTER TABLE [dbo].[USERTABLE]  WITH CHECK ADD  CONSTRAINT [fk_user_status] FOREIGN KEY([Status])
REFERENCES [dbo].[USERSTATUS] ([RecId])
GO
ALTER TABLE [dbo].[USERTABLE] CHECK CONSTRAINT [fk_user_status]
GO
ALTER TABLE [dbo].[USERTABLE]  WITH CHECK ADD  CONSTRAINT [FK_USERTABLE_USERIMAGE] FOREIGN KEY([Image])
REFERENCES [dbo].[USERIMAGE] ([RecId])
GO
ALTER TABLE [dbo].[USERTABLE] CHECK CONSTRAINT [FK_USERTABLE_USERIMAGE]
GO
USE [master]
GO
ALTER DATABASE [RakaposhiDB] SET  READ_WRITE 
GO
