IF EXISTS(select 1 from sys.databases where [name]='RakaposhiDB')
	DROP DATABASE [RakaposhiDB]
GO
USE [master]
CREATE DATABASE [RakaposhiDB]
GO

USE [RakaposhiDB]
GO
/****** Object:  Table [dbo].[ROLETABLE]    Script Date: 24/07/2022 12:33:32 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLETABLE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[Description] [nvarchar](50) NULL,
 CONSTRAINT [PK_USERROLETABLE] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERROLETABLE]    Script Date: 24/07/2022 12:33:32 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERROLETABLE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NOT NULL,
	[RoleId] [bigint] NOT NULL,
 CONSTRAINT [PK_USERROLETABLE_1] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERSTATUS]    Script Date: 24/07/2022 12:33:32 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERSTATUS](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[Status] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERTABLE]    Script Date: 24/07/2022 12:33:32 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERTABLE](
	[RecId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[Password] [nvarchar](20) NOT NULL,
	[Status] [bigint] NULL,
 CONSTRAINT [PK_USERTABLE] PRIMARY KEY CLUSTERED 
(
	[RecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERTABLE] ADD  CONSTRAINT [default_status]  DEFAULT ((2)) FOR [Status]
GO
ALTER TABLE [dbo].[USERROLETABLE]  WITH CHECK ADD  CONSTRAINT [FK_USERROLETABLE_ROLETABLE] FOREIGN KEY([RoleId])
REFERENCES [dbo].[ROLETABLE] ([RecId])
GO
ALTER TABLE [dbo].[USERROLETABLE] CHECK CONSTRAINT [FK_USERROLETABLE_ROLETABLE]
GO
ALTER TABLE [dbo].[USERROLETABLE]  WITH CHECK ADD  CONSTRAINT [FK_USERROLETABLE_USERTABLE] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERTABLE] ([RecId])
GO
ALTER TABLE [dbo].[USERROLETABLE] CHECK CONSTRAINT [FK_USERROLETABLE_USERTABLE]
GO
ALTER TABLE [dbo].[USERTABLE]  WITH CHECK ADD  CONSTRAINT [fk_user_status] FOREIGN KEY([Status])
REFERENCES [dbo].[USERTABLE] ([RecId])
GO
ALTER TABLE [dbo].[USERTABLE] CHECK CONSTRAINT [fk_user_status]
GO
USE [master]
GO
ALTER DATABASE [RakaposhiDB] SET  READ_WRITE 
GO
